import type { InventoryDashboardRow } from "./inventory-dashboard.types";

/** Données de démonstration pour le tableau de pilotage stock. */
export const mockInventoryDashboardRows: InventoryDashboardRow[] = [
  {
    codeSap: "50001234",
    codeOracle: "OR-HM-001",
    description: "HUILE MOTEUR EN VRAC",
    stockMinKg: 800,
    stockMaxKg: 3200,
    stockActuelKg: 620,
    consommationMoyenneKgJour: 18.2,
    leadTimeAchatJours: 21,
    leadTimeReceptionJours: 3,
    leadTimeLaboJours: 10,
    couvertureAcc: "Couvert ACC",
    classification: "Critique",
    dateReceptionIso: null,
    kgEnAnalyseLabo: 0,
    statutLabo: "Disponible",
  },
  {
    codeSap: "50004567",
    codeOracle: "OR-HYD-02",
    description: "HUILE HYDRAULIQUE ISO VG 46",
    stockMinKg: 1200,
    stockMaxKg: 4800,
    stockActuelKg: 2100,
    consommationMoyenneKgJour: 42.5,
    leadTimeAchatJours: 21,
    leadTimeReceptionJours: 3,
    leadTimeLaboJours: 10,
    couvertureAcc: "Couvert ACC",
    classification: "Fast",
    dateReceptionIso: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    kgEnAnalyseLabo: 350,
    statutLabo: "Stock en Analyse Labo",
  },
  {
    codeSap: "50007890",
    codeOracle: "OR-BV-03",
    description: "HUILE BOITE VITESSE SYNTHETIQUE",
    stockMinKg: 400,
    stockMaxKg: 1600,
    stockActuelKg: 380,
    consommationMoyenneKgJour: 9.1,
    leadTimeAchatJours: 21,
    leadTimeReceptionJours: 3,
    leadTimeLaboJours: 10,
    couvertureAcc: "Non couvert ACC",
    classification: "Critique",
    dateReceptionIso: null,
    kgEnAnalyseLabo: 0,
    statutLabo: "Disponible",
  },
];
